name: build

on:
  push:
    branches:
      - '**'
      - '!master'
    paths:
      - '**.py'
      - '!setup.py'
      - 'setup.cfg'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.5', '3.6', '3.7', '3.8']
    name: Testing pydeepmerge with python ${{ matrix.python }}
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies and script
        run: pip install -e .[test]

      - name: Lint with flake8
        run: flake8

      - name: Test with pytest
        run: |
          pytest

      - name: Send test to coveralls.io
        if: ${{ matrix.python == '3.7' }}  # Avoid sending multiple reports
        run: coveralls
