name: build

on:
  push:
    paths:
      - '**.py'
      - 'setup.cfg'
      - 'pytest.ini'
      - 'test-requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8']
    name: Testing acltest with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies and script
        run: pip install -r test-requirements.txt -e .

      - name: Lint with flake8
        run: flake8

      - name: Test with pytest
        run: pytest --cov=pydeepmerge tests/
