name: build

on:
  push:
    paths:
      - '**.py'
      - '!setup.py'
      - 'setup.cfg'
      - 'VERSION'

jobs:
  version-check:
    runs-on: ubuntu-latest
    name: Verify version has not been increased
    outputs:
      go-no-go: ${{ steps.version-check.outcome }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install necessary package for scripts to run
        run: pip install packaging

      - name: Verify that the version has been increased
        id: version-check
        run: python scripts/version_verification.py --equals $(python scripts/extract_version.py) $(cat VERSION)
        continue-on-error: true


  build:
    needs: version-check
    if: ${{ needs.version-check.outputs.go-no-go == 'success' || github.refs != 'ref/heads/master' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.5', '3.6', '3.7', '3.8']
    name: Testing pydeepmerge with python ${{ matrix.python }}
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies and script (python>=3.6)
        if: ${{ matrix.python != '3.5' }}
        run: pip install -e .[test]

      - name: Install dependencies and script (python==3.5)
        if: ${{ matrix.python == '3.5' }}
        run: pip install flake8 pytest pytest-cov mock && pip install -e .

      - name: Lint with flake8
        run: flake8

      - name: Test with pytest
        run: |
          pytest

      - name: Send test to coveralls.io
        if: ${{ matrix.python == '3.7' }}  # Avoid sending multiple reports
        run: coveralls
