name: release

on:
  push:
    branches:
      - master
    paths:
      - 'VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.5', '3.6', '3.7', '3.8']
    name: Testing pydeepmerge with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies and script
        run: pip install -r test-requirements.txt -e .

      - name: Lint with flake8
        run: flake8

      - name: Test with pytest
        run: pytest
  release:
    needs: build
    runs-on: ubuntu-latest
    name: Releasing package
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install wheel
        run: pip install wheel

      - name: Build release
        run: python setup.py sdist bdist_wheel

      - name: Extract version number
        run: echo "::set-env name=tag_version::$(cat VERSION)"

      - name: Extract wheel artifact name
        run: echo "::set-env name=wheel_name::$(echo dist/*.whl)"

      - name: Extract tar.gz artifact name
        run: echo "::set-env name=tar_name::$(echo dist/*.tar.gz)"

      - name: Make Github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_version }}
          release_name: Release ${{ tag_version }}
          draft: false
          prerelease: false

      - name: Upload wheel release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/${{ env.wheel_name }}
          asset_name: ${{ env.wheel_name }}

      - name: Upload tar release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/${{ env.tar_name }}
          asset_name: ${{ env.tar_name }}

      - name: Install Twine
        run: pip install twine
      
      - name: Release package
        run: twine upload dist/*
